### ISSUE TITLE
Hangman page not connected with css and script files

### ISSUE THREAD

**Issue by Suganthi2023** [Fatima1964/Mini-Games-Website#3]
Hi sundas,  Hangman HTML pages were not connected with your CSS and Script files. So I did change those to get connected with right files.

**Comment by Suganthi2023** [comment]
I hope you don't mind me doing that.

**Comment by Suganthi2023** [comment]
Also the navigation bar from index page should be on all the pages through out the website. In addition we are following the same background color for the page throughout for consistency.

**Comment by Fatima1964** [comment]
Successful connected

**Comment by Sundas-Munir** [comment]
Im working on nav bar now
