### ISSUE TITLE
wireframe link

### ISSUE THREAD

**Issue by Suganthi2023** [Fatima1964/Mini-Games-Website#4]
Hello Team,
 Here I am attaching the embed link for wireframes in figma. If you want to do wireframe for your game page, please use the link or if you provide me with your game page design I will do it for you. Here is the link
<iframe style="border: 1px solid rgba(0, 0, 0, 0.1);" width="800" height="450" src="https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FCsWbsNloSD9bgjkz88swwe%2FMini-Game-Project%3Ftype%3Ddesign%26node-id%3D0%253A1%26mode%3Ddesign%26t%3DzvnmE7IQDuz5w0A9-1" allowfullscreen></iframe>

**Comment by Suganthi2023** [comment]
If the link is not working, please let me know.

**Comment by Fatima1964** [comment]
Hi there Suganthi and team. Thanks for the wireframes.  I made some changes to the website. You might want to have a look.  Please let me know what you think.
